
version: '3.8'

services:
  datasec-agent:
    image: meli-datasec-challenge-app
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./vector_db:/app/vector_db
    ports:
      - "8000:8000"
    stop_grace_period: 1s

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:

# Nota: Para usar Ollama desde la app, la variable OLLAMA_BASE_URL debe ser http://ollama:11434